// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK9xFH3UMQcpaFvWJ7OILjl5V3qc3-QLQ',
    appId: '1:768402312298:web:8d7c93ca2a022601720e13',
    messagingSenderId: '768402312298',
    projectId: 'debit-sync',
    authDomain: 'debit-sync.firebaseapp.com',
    storageBucket: 'debit-sync.firebasestorage.app',
    measurementId: 'G-R02ZTERVXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKm487DFrWCxWcuykhCu3RgaIxCq870vQ',
    appId: '1:768402312298:android:63eae0229bfa71f7720e13',
    messagingSenderId: '768402312298',
    projectId: 'debit-sync',
    storageBucket: 'debit-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArtBukORIEpe6Ys_UVeBpxF_4YBLEdeNk',
    appId: '1:768402312298:ios:d0d39ef2aa010d2f720e13',
    messagingSenderId: '768402312298',
    projectId: 'debit-sync',
    storageBucket: 'debit-sync.firebasestorage.app',
    iosClientId: '768402312298-f45s0i50gh12iur84ttqnkirtqv1nvf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.debitSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArtBukORIEpe6Ys_UVeBpxF_4YBLEdeNk',
    appId: '1:768402312298:ios:d0d39ef2aa010d2f720e13',
    messagingSenderId: '768402312298',
    projectId: 'debit-sync',
    storageBucket: 'debit-sync.firebasestorage.app',
    iosClientId: '768402312298-f45s0i50gh12iur84ttqnkirtqv1nvf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.debitSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK9xFH3UMQcpaFvWJ7OILjl5V3qc3-QLQ',
    appId: '1:768402312298:web:3a8b507b37c64617720e13',
    messagingSenderId: '768402312298',
    projectId: 'debit-sync',
    authDomain: 'debit-sync.firebaseapp.com',
    storageBucket: 'debit-sync.firebasestorage.app',
    measurementId: 'G-FPNSTD8R65',
  );
}
