import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'firebase_options.dart';

/// Application entry point.
///
/// Firebase is initialized asynchronously via the platform-specific options
/// generated by the FlutterFire CLI (`flutterfire configure`).
/// [WidgetsFlutterBinding.ensureInitialized] is required to allow async work
/// before the Flutter engine is ready.
///
/// [ProviderScope] is the root Riverpod scope — it must wrap the entire widget
/// tree so that all providers are accessible throughout the app.
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    const ProviderScope(
      child: DebitSyncApp(),
    ),
  );
}
